version: '3.3'


services:

  suricata:
     container_name: suricata
     restart: always
     env_file:
             - 'env.suricata'
     network_mode: "host"
     cap_add: 
            - NET_ADMIN
            - SYS_NICE
            - NET_RAW
     image: jasonish/suricata:latest
     volumes:
             - ./suricata/log:/var/log/suricata
             - ./suricata/etc:/etc/suricata
          #  - ./suricata/lib:/var/lib/suricata
  

  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      - ./data_influxdb:/var/lib/influxdb

  telegraf:
    image: telegraf:1.16.3
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro


  grafana:
    image: grafana/grafana:7.3.7
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    links:
      - influxdb
    volumes:
      - ./data_grafana:/var/lib/grafana



volumes:
  data_influxdb:
  data_grafana:
  telegraf.conf:
  suricata:        
